version: '3'

services:
  # enables live reload
  celery:
    volumes:
      - .:/usr/src/app
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery worker --app clustarr_backend.celery --loglevel=info

  # enables live reload
  flask:
    volumes:
      - .:/usr/src/app
    command: python run.py
