version: '3'

services:
  # redis is used by app and celery to exchange background task information
  redis:
    image: redis:alpine
    expose:
      - 6379

  # this service builds the image used by celery and app and exits afterwards
  build:
    image: app
    build: .

  # celery executes playbooks in the background
  # we need to pass through the ansible project path that contains the playbooks,
  # the ssh keys to connect to remote hosts and the proxmox inventory script
  celery:
    image: app
    restart: unless-stopped
    environment:
      ANSIBLE_PROJECT_PATH: /ansible
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - /home/lucas/Projects/clustarr/ansible:/ansible:ro
      - /home/lucas/.ssh:/root/.ssh/:ro
      - /etc/ansible/proxmox.py:/etc/ansible/proxmox.py:ro
      - /etc/ansible/proxmox.json:/etc/ansible/proxmox.json:ro
    depends_on:
      - build
      - redis
    command: celery worker --app main.celery --loglevel=info

  # flask provides the api and forwards playbook tasks to the celery service
  flask:
    image: app
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      ANSIBLE_PROJECT_PATH: /ansible
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - /home/lucas/Projects/clustarr/ansible:/ansible:ro
      - /etc/ansible/proxmox.py:/etc/ansible/proxmox.py:ro
      - /etc/ansible/proxmox.json:/etc/ansible/proxmox.json:ro
    depends_on:
      - build
      - celery
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
